import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
import { AppProvider } from "@/components/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ST PIZZA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative h-full font-sans antialiased overflow-x-hidden",
          inter.className
        )}
      >
        <main className="relative w-full py-4 min-h-screen">
          <div className="flex-grow flex-1">
            <AppProvider>
              <Navbar />
              {children}
              <Footer />
            </AppProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
